Repository boostcamp-2020/Project18-B-iOS-BoostRunClub, pull requests merged in 2020-12, with the labels that each got.

#42 GoalTypeViewModel 테스트코드 작성
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/ViewModels/GoalTypeViewModelTest.swift
Labels: 🏷 test🧪

#50 (#8) 러닝을 시작할 수 있다
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityCoordinator.swift
  BoostRunClub/Coordinators/AppCoordinator.swift
  BoostRunClub/Coordinators/Coordinator.swift
  BoostRunClub/Coordinators/LoginCoordinator.swift
  BoostRunClub/Coordinators/PausedRunningCoordinator.swift
  BoostRunClub/Coordinators/PrepareRunCoordinator.swift
  BoostRunClub/Coordinators/ProfileCoordinator.swift
  BoostRunClub/Coordinators/RunningCoordinator.swift
  BoostRunClub/Coordinators/RunningInfoCoordinator.swift
  BoostRunClub/Coordinators/RunningMapCoordinator.swift
  BoostRunClub/Coordinators/RunningPageCoordinator.swift
  BoostRunClub/Coordinators/SplitsViewCoordinator.swift
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/Extensions/CaseIterable+.swift
  BoostRunClub/Extensions/Notification.name.swift
  BoostRunClub/Extensions/TimerInterval+String.swift
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Models/RunningInfoType.swift
  BoostRunClub/SceneDelegate.swift
  BoostRunClub/Services/LocationProvider.swift
  BoostRunClub/Services/RunningDataProvider.swift
  BoostRunClub/ViewModels/GoalTypeViewModelTest.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClub/ViewModels/RunningPageViewModel.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/RunningInfoViewController.swift
  BoostRunClubTests/Mocks/LocationProviderMock.swift
Labels: 🏷️ feature 🚀

#52 (#51) running data provider 추상화
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Services/EventTimer.swift
  BoostRunClub/Services/RunningDataProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
Labels: 🏷️ refactoring ✒

#54 (#53) Running 시작 애니메이션, Running Pause 애니메이션
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
  BoostRunClub/Views/CountDownView.swift
Labels: 🏷️ feature 🚀

#56 (#55) CoreLocation Background 실행 조절 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/AppCoordinator.swift
  BoostRunClub/Coordinators/PausedRunningCoordinator.swift
  BoostRunClub/Extensions/Notification.name.swift
  BoostRunClub/Extensions/UIButton+setSFSymbol.swift
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Services/EventTimer.swift
  BoostRunClub/Services/LocationProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClub/Views/CircleButton.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
  BoostRunClub/Views/Controllers/RunningInfoViewController.swift
  BoostRunClub/Views/CountDownView.swift
  BoostRunClubTests/Mocks/LocationProviderMock.swift
Labels: 🏷️ feature 🚀

#60 (#58) GoalTypeVC goalType Cell 스타일 적용
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Extensions/UIButton+setSFSymbol.swift
  BoostRunClub/Extensions/UIImage+SFSymbol.swift
  BoostRunClub/Views/Cells/GoalTypeCell.swift
  BoostRunClub/Views/CircleButton.swift
  BoostRunClub/Views/Controllers/GoalTypeViewController.swift
  BoostRunClub/Views/RunDataView.swift
Labels: 🏷️ feature 🚀

#65 Feature/63
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Extensions/UIView+otificationFeedback.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/PrepareRunViewModelTest.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
  BoostRunClub/Views/Controllers/RunningInfoViewController.swift
Labels: 🏷️ feature 🚀

#66 (#64) feat: 맵 경로 표시, Running Data 자료구조 설계
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Models/RunningSlice.swift
  BoostRunClub/Models/RunningSplit.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
Labels: 🏷️ feature 🚀

#70 (#69) fix: (P1) running data provider 초기 세팅 버그 수정
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Services/RunningDataService.swift
Labels: 🏷️ bug :beetle:

#71 (#69) fix: (P1) running data provider 초기 세팅 버그 수정
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Services/RunningDataService.swift
Labels: 🏷️ bug :beetle:

#73 케이던스, 칼로리, BPM 연산 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Models/MotionType.swift
  BoostRunClub/Models/RunningInfoType.swift
  BoostRunClub/Services/LocationProvider.swift
  BoostRunClub/Services/MotionProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/SupportingFiles/Info.plist
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClubTests/Info.plist
Labels: 🏷️ feature 🚀

#76 (#74) Activity, ActivityDetail, RunningSplit Core Data 모델 구성 및 Fetching
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/AppCoordinator.swift
  BoostRunClub/Coordinators/RunningCoordinator.swift
  BoostRunClub/Coordinators/RunningPageCoordinator.swift
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/CoreData/BRCModel.xcdatamodeld/BRCModel.xcdatamodel/contents
  BoostRunClub/CoreData/ZActivity+Activity.swift
  BoostRunClub/CoreData/ZActivityDetail+ActivityDetail.swift
  BoostRunClub/CoreData/ZRunningSplit+RunningSplit.swift
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Models/Activity.swift
  BoostRunClub/Models/ActivityDetail.swift
  BoostRunClub/Models/GoalType.swift
  BoostRunClub/Models/Location.swift
  BoostRunClub/Models/RunningSlice.swift
  BoostRunClub/Models/RunningSplit.swift
  BoostRunClub/Services/ActivityProvider.swift
  BoostRunClub/Services/CoreDataService.swift
  BoostRunClub/Services/MotionProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#78 (#77) Dependency Factory 리팩토링
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityCoordinator.swift
  BoostRunClub/Coordinators/AppCoordinator.swift
  BoostRunClub/Coordinators/Coordinator.swift
  BoostRunClub/Coordinators/LoginCoordinator.swift
  BoostRunClub/Coordinators/PausedRunningCoordinator.swift
  BoostRunClub/Coordinators/PrepareRunCoordinator.swift
  BoostRunClub/Coordinators/ProfileCoordinator.swift
  BoostRunClub/Coordinators/RunningCoordinator.swift
  BoostRunClub/Coordinators/RunningInfoCoordinator.swift
  BoostRunClub/Coordinators/RunningMapCoordinator.swift
  BoostRunClub/Coordinators/RunningPageCoordinator.swift
  BoostRunClub/Coordinators/SplitsViewCoordinator.swift
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Factory/Extensions/Factory+ActivityDetailScene.swift
  BoostRunClub/Factory/Extensions/Factory+ActivityScene.swift
  BoostRunClub/Factory/Extensions/Factory+GoalTypeScene.swift
  BoostRunClub/Factory/Extensions/Factory+GoalValueSetupScene.swift
  BoostRunClub/Factory/Extensions/Factory+LoginScene.swift
  BoostRunClub/Factory/Extensions/Factory+PausedRunningScene.swift
  BoostRunClub/Factory/Extensions/Factory+PrepareRunScene.swift
  BoostRunClub/Factory/Extensions/Factory+ProfileScene.swift
  BoostRunClub/Factory/Extensions/Factory+RunningInfoScene.swift
  BoostRunClub/Factory/Extensions/Factory+RunningMapScene.swift
  BoostRunClub/Factory/Extensions/Factory+RunningPageContainer.swift
  BoostRunClub/Factory/Extensions/Factory+SplitScene.swift
  BoostRunClub/Factory/Extensions/Factory+TabBarContainer.swift
  BoostRunClub/SceneDelegate.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
Labels: 0_Merge: master, 🏷️ refactoring ✒

#80 VC, VM, Coor 메모리 누수 해결
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/Coordinator.swift
  BoostRunClub/Coordinators/PausedRunningCoordinator.swift
  BoostRunClub/Coordinators/PrepareRunCoordinator.swift
  BoostRunClub/Coordinators/ProfileCoordinator.swift
  BoostRunClub/Coordinators/RunningCoordinator.swift
  BoostRunClub/Coordinators/RunningInfoCoordinator.swift
  BoostRunClub/Coordinators/RunningPageCoordinator.swift
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/ViewModels/GoalTypeViewModel.swift
  BoostRunClub/ViewModels/GoalValueSetupViewModel.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClub/ViewModels/RunningMapViewModel.swift
  BoostRunClub/ViewModels/RunningPageViewModel.swift
  BoostRunClub/ViewModels/SplitsViewModel.swift
  BoostRunClub/Views/Controllers/GoalTypeViewController.swift
  BoostRunClub/Views/Controllers/GoalValueSetupViewController.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
  BoostRunClub/Views/Controllers/RunningInfoViewController.swift
  BoostRunClub/Views/Controllers/RunningMapViewController.swift
  BoostRunClub/Views/Controllers/RunningPageViewController.swift
  BoostRunClub/Views/Controllers/SplitsViewController.swift
Labels: 0_Merge: master, 🏷️ bug :beetle:

#96 (#89) feat: running map scene 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/RunningMapCoordinator.swift
  BoostRunClub/Factory/Extensions/Factory+RunningMapScene.swift
  BoostRunClub/ViewModels/RunningMapViewModel.swift
  BoostRunClub/Views/CircleButton.swift
  BoostRunClub/Views/Controllers/RunningMapViewController.swift
  BoostRunClub/Views/Controllers/RunningPageViewController.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#99 (#98) refactor: mapview user track mode 관련 불필요한 코드 제거
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
Labels: 0_Merge: master, 🏷️ refactoring ✒

#100 (#81) Activity Scene VM/VC 기본 구조와 View 구성
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityCoordinator.swift
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/Extensions/UIStackView+Make.swift
  BoostRunClub/Factory/Extensions/Factory+ActivityScene.swift
  BoostRunClub/Models/ActivityFilterType.swift
  BoostRunClub/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  BoostRunClub/ViewModels/ActivityViewModel.swift
  BoostRunClub/ViewModels/CellConfigurable/ActivityStatistic.swift
  BoostRunClub/ViewModels/CellConfigurable/ActivityTotal.swift
  BoostRunClub/Views/ActivityFooterView.swift
  BoostRunClub/Views/ActivityTableView.swift
  BoostRunClub/Views/ActivityTotalView.swift
  BoostRunClub/Views/Cells/ActivityCellView.swift
  BoostRunClub/Views/Cells/ActivityStatisticCellView.swift
  BoostRunClub/Views/Controllers/ActivityViewController.swift
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
  BoostRunClub/Views/RoundSegmentControl.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#103 (#25 #26) ActivityScene TotalView 연결 및 Date PickerView 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/.swiftlint.yml
  BoostRunClub/Coordinators/ActivityCoordinator.swift
  BoostRunClub/Coordinators/RunningPageCoordinator.swift
  BoostRunClub/CoreData/BRCModel.xcdatamodeld/BRCModel.xcdatamodel/contents
  BoostRunClub/CoreData/ZActivity+Activity.swift
  BoostRunClub/CoreData/ZActivityDetail+ActivityDetail.swift
  BoostRunClub/CoreData/ZRunningSplit+RunningSplit.swift
  BoostRunClub/Extensions/Date+DateRange.swift
  BoostRunClub/Extensions/Date+String.swift
  BoostRunClub/Extensions/DateFormatter+Common.swift
  BoostRunClub/Extensions/TimerInterval+String.swift
  BoostRunClub/Factory/Extensions/Factory+ActivityScene.swift
  BoostRunClub/Factory/Extensions/Factory+RunningPageContainer.swift
  BoostRunClub/Models/Activity.swift
  BoostRunClub/Models/ActivityDetail.swift
  BoostRunClub/Models/ActivityFilterType.swift
  BoostRunClub/Models/DateRange.swift
  BoostRunClub/Models/RunningSplit.swift
  BoostRunClub/Services/ActivityProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/ActivityDateFilterViewModel.swift
  BoostRunClub/ViewModels/ActivityViewModel.swift
  BoostRunClub/ViewModels/CellConfigurable/ActivityStatistic.swift
  BoostRunClub/ViewModels/CellConfigurable/ActivityTotal.swift
  BoostRunClub/ViewModels/CellConfigurable/ActivityTotalConfig.swift
  BoostRunClub/ViewModels/PrepareRunViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModelTest.swift
  BoostRunClub/Views/ActivityTotalView.swift
  BoostRunClub/Views/Cells/ActivityCellView.swift
  BoostRunClub/Views/Cells/ActivityStatisticCellView.swift
  BoostRunClub/Views/Controllers/ActivityDateFilterViewController.swift
  BoostRunClub/Views/Controllers/ActivityViewController.swift
  BoostRunClub/Views/DateFilterSheetView.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#104 (#97) feat: running split scene 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/SplitsViewCoordinator.swift
  BoostRunClub/Extensions/UIStackView+Make.swift
  BoostRunClub/Extensions/UIView+identifier.swift
  BoostRunClub/Extensions/UIView+notificationFeedback.swift
  BoostRunClub/Factory/Extensions/Factory+SplitScene.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/RunningSplitCellViewModel.swift
  BoostRunClub/ViewModels/SplitsViewModel.swift
  BoostRunClub/Views/Cells/RunningSplitCell.swift
  BoostRunClub/Views/Controllers/SplitsViewController.swift
  BoostRunClub/Views/RunningSplitHeaderView.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#106 (#91) feat: Location accuracy에 따른 값 전송 유무 로직 추가
  BoostRunClub/Services/LocationProvider.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#107 (#88) Motion Type에 따라 자동으로 러닝을 일시정지 및 재시작한다
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Models/MotionType.swift
  BoostRunClub/Services/MotionProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
Labels: 0_Merge: master, 🏷️ feature 🚀, 🏷️ refactoring ✒

#115 (#114) ActivityListScene 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityCoordinator.swift
  BoostRunClub/Coordinators/ActivityListCoordinator.swift
  BoostRunClub/Factory/Extensions/Factory+ActivityListScene.swift
  BoostRunClub/ViewModels/ActivityListViewModel.swift
  BoostRunClub/ViewModels/ActivityViewModel.swift
  BoostRunClub/ViewModels/CellConfigurable/ActivityListItem.swift
  BoostRunClub/Views/ActivityScene/ActivitiesContainerCellView.swift
  BoostRunClub/Views/ActivityScene/ActivityCellView.swift
  BoostRunClub/Views/ActivityScene/ActivityCollectionView.swift
  BoostRunClub/Views/ActivityScene/ActivityFooterView.swift
  BoostRunClub/Views/ActivityScene/ActivityListHeaderView.swift
  BoostRunClub/Views/ActivityScene/ActivityStatisticCellView.swift
  BoostRunClub/Views/ActivityScene/ActivityTableView.swift
  BoostRunClub/Views/ActivityScene/ActivityTotalView.swift
  BoostRunClub/Views/ActivityScene/DateFilterSheetView.swift
  BoostRunClub/Views/Controllers/ActivityDateFilterViewController.swift
  BoostRunClub/Views/Controllers/ActivityListViewController.swift
  BoostRunClub/Views/Controllers/ActivityViewController.swift
  BoostRunClub/Views/DataSource/ActivityDataSource.swift
  BoostRunClub/Views/DataSource/ActivityListDataSource.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#118 (#117) Activity 타이틀 시간경과에 따라 변경
  BoostRunClub/Extensions/Date+DateRange.swift
  BoostRunClub/Extensions/Date+String.swift
  BoostRunClub/Extensions/DateFormatter+Common.swift
  BoostRunClub/Models/Activity.swift
  BoostRunClub/Models/ActivityFilterType.swift
  BoostRunClub/ViewModels/ActivityListViewModel.swift
  BoostRunClub/ViewModels/ActivityViewModel.swift
  BoostRunClub/ViewModels/CellConfigurable/ActivityListItem.swift
  BoostRunClub/Views/ActivityScene/ActivityCellView.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#122 (#90) [Profile] 프로필 정보를 확인하고 편집할 수 있다
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ProfileCoordinator.swift
  BoostRunClub/Extensions/Data+SaveAndLoadData.swift
  BoostRunClub/Extensions/URL+Documents.swift
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Factory/Extensions/Factory+EditProfileScene.swift
  BoostRunClub/Factory/Extensions/Factory+ProfileScene.swift
  BoostRunClub/Models/Profile.swift
  BoostRunClub/Services/DefaultsProvider.swift
  BoostRunClub/SupportingFiles/Assets.xcassets/customBackground.colorset/Contents.json
  BoostRunClub/SupportingFiles/Info.plist
  BoostRunClub/ViewModels/EditProfileViewModel.swift
  BoostRunClub/ViewModels/ProfileViewModel.swift
  BoostRunClub/Views/Controllers/EditProfileViewController.swift
  BoostRunClub/Views/Controllers/ProfileViewController.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#123 (#121) 러닝 중단 후 저장시 맵과 경로 스냅샷 저장 기능 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/CoreData/BRCModel.xcdatamodeld/BRCModel.xcdatamodel/contents
  BoostRunClub/CoreData/ZActivityDetail+ActivityDetail.swift
  BoostRunClub/Extensions/Date+DateRange.swift
  BoostRunClub/Extensions/MKCoordinateRegion+Make.swift
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Models/ActivityDetail.swift
  BoostRunClub/Services/ActivityProvider.swift
  BoostRunClub/Services/LocationProvider.swift
  BoostRunClub/Services/MapSnapShotService/MapSnapShotService.swift
  BoostRunClub/Services/MapSnapShotService/MapSnapShotSubscription.swift
  BoostRunClub/Services/MapSnapShotService/RouteDrawer.swift
  BoostRunClub/Services/MapSnapShotService/RouteSnapShotProcessor.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/ActivityListViewModel.swift
  BoostRunClub/ViewModels/ActivityViewModel.swift
  BoostRunClub/ViewModels/CellConfigurable/ActivityTotalConfig.swift
  BoostRunClub/Views/ActivityScene/ActivityCellView.swift
  BoostRunClub/Views/ActivityScene/ActivityTotalView.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#125 (#124) feat: TabBar Icon 추가
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/Factory/Extensions/Factory+TabBarContainer.swift
  BoostRunClub/SupportingFiles/Assets.xcassets/Image.imageset/Contents.json
  BoostRunClub/SupportingFiles/Assets.xcassets/activity.imageset/Contents.json
  BoostRunClub/SupportingFiles/Assets.xcassets/activity.imageset/clock.png
  BoostRunClub/SupportingFiles/Assets.xcassets/profile.imageset/Contents.json
  BoostRunClub/SupportingFiles/Assets.xcassets/profile.imageset/user.png
  BoostRunClub/SupportingFiles/Assets.xcassets/running.imageset/Contents.json
  BoostRunClub/SupportingFiles/Assets.xcassets/running.imageset/running (1).png
Labels: 0_Merge: master, 🏷️ feature 🚀

#133 (#129) feat: edit profile scene scrollview으로 교체
  BoostRunClub/Models/Profile.swift
  BoostRunClub/ViewModels/EditProfileViewModel.swift
  BoostRunClub/Views/Controllers/EditProfileViewController.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#132 (#105) feat: 러닝 맵, 구간 화면 하단에 표시되는 버튼 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/Factory/Extensions/Factory+RunningPageContainer.swift
  BoostRunClub/Services/EventTimer.swift
  BoostRunClub/SupportingFiles/Info.plist
  BoostRunClub/ViewModels/RunningMapViewModel.swift
  BoostRunClub/ViewModels/RunningPageViewModel.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/RunningPageViewController.swift
  BoostRunClub/Views/Controllers/SplitsViewController.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#135 (#128) ActivityDetail 첫 화면 구성과 기본 데이터 연결
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityCoordinator.swift
  BoostRunClub/Coordinators/ActivityDetailCoordinator.swift
  BoostRunClub/CoreData/BRCModel.xcdatamodeld/BRCModel.xcdatamodel/contents
  BoostRunClub/CoreData/ZActivityDetail+ActivityDetail.swift
  BoostRunClub/CoreData/ZRunningSplit+RunningSplit.swift
  BoostRunClub/Extensions/Date+String.swift
  BoostRunClub/Extensions/DateFormatter+Common.swift
  BoostRunClub/Extensions/MKCoordinateRegion+Make.swift
  BoostRunClub/Extensions/UILabel+Make.swift
  BoostRunClub/Factory/Extensions/Factory+ActivityDetailScene.swift
  BoostRunClub/Models/ActivityDetail.swift
  BoostRunClub/Models/RunningSplit.swift
  BoostRunClub/Services/ActivityProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/ActivityDetailViewModel.swift
  BoostRunClub/ViewModels/ActivityListViewModel.swift
  BoostRunClub/ViewModels/ActivityViewModel.swift
  BoostRunClub/ViewModels/Configurable/ActivityDetailConfig.swift
  BoostRunClub/ViewModels/Configurable/ActivityListItem.swift
  BoostRunClub/ViewModels/Configurable/ActivityTotalConfig.swift
  BoostRunClub/Views/ActivityDetailScene/DetailMapView.swift
  BoostRunClub/Views/ActivityDetailScene/DetailSplitsTableView.swift
  BoostRunClub/Views/ActivityDetailScene/DetailSplitsView.swift
  BoostRunClub/Views/ActivityDetailScene/DetailTitleView.swift
  BoostRunClub/Views/ActivityDetailScene/DetailTotalView.swift
  BoostRunClub/Views/ActivityDetailScene/SimpleSplitViewCell.swift
  BoostRunClub/Views/ActivityScene/ActivitiesContainerCellView.swift
  BoostRunClub/Views/Controllers/ActivityDetailViewController.swift
  BoostRunClub/Views/Controllers/ActivityViewController.swift
  BoostRunClub/Views/DataSource/ActivityDetailDataSource.swift
  BoostRunClub/Views/NikeLabel.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#139 (#128, #138) detail 화면 시작 애니메이션 및 Split Cell 레이아웃 수정
  BoostRunClub/Coordinators/ActivityDetailCoordinator.swift
  BoostRunClub/Models/RunningSlice.swift
  BoostRunClub/Models/RunningSplit.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/ActivityDetailViewModel.swift
  BoostRunClub/Views/ActivityDetailScene/DetailMapView.swift
  BoostRunClub/Views/ActivityDetailScene/DetailSplitsView.swift
  BoostRunClub/Views/ActivityDetailScene/DetailTotalView.swift
  BoostRunClub/Views/ActivityDetailScene/SimpleSplitViewCell.swift
  BoostRunClub/Views/Controllers/ActivityDetailViewController.swift
  BoostRunClub/Views/DataSource/ActivityDetailDataSource.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#143 (#142) Style 및 SimpleSplitCellView avgPace별 배경 막대그래프 수치 적용
  BoostRunClub/Coordinators/ActivityDetailCoordinator.swift
  BoostRunClub/Factory/Extensions/Factory+RunningPageContainer.swift
  BoostRunClub/ViewModels/Configurable/ActivityTotalConfig.swift
  BoostRunClub/ViewModels/GoalValueSetupViewModelTest.swift
  BoostRunClub/Views/ActivityDetailScene/DetailTotalView.swift
  BoostRunClub/Views/ActivityDetailScene/SimpleSplitViewCell.swift
  BoostRunClub/Views/ActivityScene/ActivityCellView.swift
  BoostRunClub/Views/ActivityScene/ActivityTotalView.swift
  BoostRunClub/Views/CircleLongPressButton.swift
  BoostRunClub/Views/Controllers/ActivityViewController.swift
  BoostRunClub/Views/Controllers/EditProfileViewController.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/RunningMapViewController.swift
  BoostRunClub/Views/DataSource/ActivityDataSource.swift
  BoostRunClub/Views/DataSource/ActivityDetailDataSource.swift
Labels: 0_Merge: master, 🏷️ feature 🚀, 🏷️ style :art:

#148 (#146) 코디네이터 연결 및 해제 리펙토링
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityCoordinator.swift
  BoostRunClub/Coordinators/ActivityDetailCoordinator.swift
  BoostRunClub/Coordinators/ActivityListCoordinator.swift
  BoostRunClub/Coordinators/AppCoordinator.swift
  BoostRunClub/Coordinators/Coordinator.swift
  BoostRunClub/Coordinators/LoginCoordinator.swift
  BoostRunClub/Coordinators/PausedRunningCoordinator.swift
  BoostRunClub/Coordinators/PrepareRunCoordinator.swift
  BoostRunClub/Coordinators/ProfileCoordinator.swift
  BoostRunClub/Coordinators/RunningCoordinator.swift
  BoostRunClub/Coordinators/RunningInfoCoordinator.swift
  BoostRunClub/Coordinators/RunningMapCoordinator.swift
  BoostRunClub/Coordinators/RunningPageCoordinator.swift
  BoostRunClub/Coordinators/SplitsViewCoordinator.swift
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/Models/GoalType.swift
  BoostRunClub/SceneDelegate.swift
  BoostRunClub/ViewModels/ActivityDateFilterViewModel.swift
  BoostRunClub/ViewModels/ActivityDetailViewModel.swift
  BoostRunClub/ViewModels/ActivityListViewModel.swift
  BoostRunClub/ViewModels/ActivityViewModel.swift
  BoostRunClub/ViewModels/EditProfileViewModel.swift
  BoostRunClub/ViewModels/GoalTypeViewModel.swift
  BoostRunClub/ViewModels/GoalValueSetupViewModel.swift
  BoostRunClub/ViewModels/GoalValueSetupViewModelTest.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModelTest.swift
  BoostRunClub/ViewModels/ProfileViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClub/ViewModels/RunningMapViewModel.swift
  BoostRunClub/ViewModels/RunningPageViewModel.swift
  BoostRunClub/ViewModels/SplitsViewModel.swift
  BoostRunClub/Views/Controllers/ActivityDateFilterViewController.swift
  BoostRunClub/Views/Controllers/ActivityDetailViewController.swift
  BoostRunClub/Views/Controllers/ActivityListViewController.swift
  BoostRunClub/Views/Controllers/ActivityViewController.swift
  BoostRunClub/Views/Controllers/EditProfileViewController.swift
  BoostRunClub/Views/Controllers/GoalTypeViewController.swift
  BoostRunClub/Views/Controllers/GoalValueSetupViewController.swift
  BoostRunClub/Views/Controllers/LoginViewController.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
  BoostRunClub/Views/Controllers/ProfileViewController.swift
  BoostRunClub/Views/Controllers/RunningInfoViewController.swift
  BoostRunClub/Views/Controllers/RunningMapViewController.swift
  BoostRunClub/Views/Controllers/RunningPageViewController.swift
  BoostRunClub/Views/Controllers/SplitsViewController.swift
Labels: 0_Merge: master, 🏷️ refactoring ✒

#149 (#147) 러닝 중 기본적인 음성 피드백 지원 - 시작, 재시작, 일시정지
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Models/RunningEvent.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/RunningPageViewModel.swift
  BoostRunClub/Views/Controllers/RunningPageViewController.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#152 (#130) 구간 상세화면 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityDetailCoordinator.swift
  BoostRunClub/CoreData/BRCModel.xcdatamodeld/BRCModel.xcdatamodel/contents
  BoostRunClub/CoreData/ZActivity+Activity.swift
  BoostRunClub/Extensions/Date+String.swift
  BoostRunClub/Extensions/DateFormatter+Common.swift
  BoostRunClub/Extensions/UINavigationController+setStatusBar.swift
  BoostRunClub/Factory/Extensions/Factory+ActivityDetailScene.swift
  BoostRunClub/Models/Activity.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/SplitInfoDetailViewModel.swift
  BoostRunClub/ViewModels/SplitsViewModel.swift
  BoostRunClub/Views/Cells/RunningSplitCell.swift
  BoostRunClub/Views/Controllers/SplitInfoDetailViewController.swift
  BoostRunClub/Views/Controllers/SplitsViewController.swift
  BoostRunClub/Views/DataSource/SplitDatailSplitDataSource.swift
  BoostRunClub/Views/DataSource/SplitInfoDetailDataSource.swift
  BoostRunClub/Views/SplitInfoDetailScene/SplitDatailSplitCell.swift
  BoostRunClub/Views/SplitInfoDetailScene/SplitDetailDateInfoView.swift
  BoostRunClub/Views/SplitInfoDetailScene/SplitDetailInfoCell.swift
  BoostRunClub/Views/SplitInfoDetailScene/SplitDetailSplitHeaderView.swift
  BoostRunClub/Views/SplitInfoDetailScene/SplitHeaderView.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#155 (#154) feat: CoreML Activity Classifier를 이용한 모션 타입 감지
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/CoreML/BRCActivityClassifierA.mlmodel
  BoostRunClub/Models/MotionType.swift
  BoostRunClub/Services/MotionProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#160 (#156) pace별 경로 gradient 표시
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Extensions/UIColor+RGBA.swift
  BoostRunClub/Models/Location.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/Views/ActivityDetailScene/DetailMapView.swift
  BoostRunClub/Views/Renderer/BasicRouteOverlay.swift
  BoostRunClub/Views/Renderer/BasicRouteRenderer.swift
  BoostRunClub/Views/Renderer/GradientRouteOverlay.swift
  BoostRunClub/Views/Renderer/GradientRouteRenderer.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#162 (#134) RouteDetailView 구현 및 custom annotation 추가
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityDetailCoordinator.swift
  BoostRunClub/Extensions/CLLocationCoordinate+computeSplitCoordinate.swift
  BoostRunClub/Extensions/UIImage+CustomAnnotation.swift
  BoostRunClub/Factory/Extensions/Factory+RouteDetailScene.swift
  BoostRunClub/Utilities.swift
  BoostRunClub/ViewModels/ActivityDetailViewModel.swift
  BoostRunClub/ViewModels/RouteDetailViewModel.swift
  BoostRunClub/Views/ActivityDetailScene/DetailMapView.swift
  BoostRunClub/Views/Controllers/RouteDetailViewController.swift
  BoostRunClub/Views/Renderer/BasicRouteOverlay.swift
  BoostRunClub/Views/Renderer/GradientRouteRenderer.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#165 (#164) gradient 계산 RGB -> Hue Saturation Brightness로 변경
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Extensions/UIColor+Components.swift
  BoostRunClub/Views/Renderer/GradientRouteOverlay.swift
  BoostRunClub/Views/Renderer/GradientRouteRenderer.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#166 버그 수정 및 러닝 맵 기능 구현
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/RunningMapCoordinator.swift
  BoostRunClub/Coordinators/RunningPageCoordinator.swift
  BoostRunClub/Extensions/UIButton+setArrowImage.swift
  BoostRunClub/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  BoostRunClub/ViewModels/RunningMapViewModel.swift
  BoostRunClub/ViewModels/RunningPageViewModel.swift
  BoostRunClub/Views/CircleButton.swift
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
  BoostRunClub/Views/Controllers/RunningMapViewController.swift
  BoostRunClub/Views/Controllers/RunningPageViewController.swift
  BoostRunClub/Views/SplitInfoDetailScene/SplitDatailSplitCell.swift
  BoostRunClub/Views/SplitInfoDetailScene/SplitDetailDateInfoView.swift
  BoostRunClub/Views/SplitInfoDetailScene/SplitHeaderView.swift
Labels: 0_Merge: master, 🏷️ feature 🚀, 🏷️ bug :beetle:

#167 (#163) 프로필 버튼 사이즈, 이미지, 액션 추가
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Coordinators/ActivityCoordinator.swift
  BoostRunClub/Coordinators/PrepareRunCoordinator.swift
  BoostRunClub/Coordinators/TabBarCoordinator.swift
  BoostRunClub/Extensions/UIImage+SFSymbol.swift
  BoostRunClub/Factory/Extensions/Factory+TabBarContainer.swift
  BoostRunClub/ViewModels/ActivityViewModel.swift
  BoostRunClub/ViewModels/EditProfileViewModel.swift
  BoostRunClub/ViewModels/PrepareRunViewModel.swift
  BoostRunClub/Views/Controllers/ActivityViewController.swift
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
  BoostRunClub/Views/ProfileButton.swift.swift
Labels: 0_Merge: master, 🏷️ feature 🚀

#170 (#169) style: App Icon 추가
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/1024.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/114.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/120.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/180.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/29.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/40.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/57.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/58.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/60.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/80.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/87.png
  BoostRunClub/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🏷️ style :art:

#176 (#172) style: 시작 버튼 사이즈 및 제약 사항 수정
  BoostRunClub/Views/Controllers/PrepareRunViewController.swift
Labels: 🏷️ style :art:

#177 (#174) style: goal type setup view 두께 조절 및 뷰가 최대한 유사하도록 조정
  BoostRunClub/Views/Cells/GoalTypeCell.swift
  BoostRunClub/Views/Controllers/GoalTypeViewController.swift
Labels: 0_Merge: master, 🏷️ style :art:

#178 (#168) refactor: RunningDataProvider 역할 분리 리펙터링
  BoostRunClub.xcodeproj/project.pbxproj
  BoostRunClub/Extensions/CLLocationCoordinate+computeSplitCoordinate.swift
  BoostRunClub/Factory/DependencyFactory.swift
  BoostRunClub/Factory/Extensions/Factory+PausedRunningScene.swift
  BoostRunClub/Factory/Extensions/Factory+RunningInfoScene.swift
  BoostRunClub/Factory/Extensions/Factory+RunningMapScene.swift
  BoostRunClub/Factory/Extensions/Factory+RunningPageContainer.swift
  BoostRunClub/Factory/Extensions/Factory+SplitScene.swift
  BoostRunClub/Models/RunningSplit.swift
  BoostRunClub/Models/RunningState.swift
  BoostRunClub/Services/MotionProvider.swift
  BoostRunClub/Services/PedometerProvider.swift
  BoostRunClub/Services/RunningDataService.swift
  BoostRunClub/Services/RunningService/RunningBoard.swift
  BoostRunClub/Services/RunningService/RunningRecoder.swift
  BoostRunClub/Services/RunningService/RunningServiceType.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClub/ViewModels/RunningMapViewModel.swift
  BoostRunClub/ViewModels/RunningPageViewModel.swift
  BoostRunClub/ViewModels/SplitsViewModel.swift
  BoostRunClub/Views/Controllers/GoalTypeViewController.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Renderer/GradientRouteOverlay.swift
Labels: 0_Merge: master, 🏷️ refactoring ✒

#182 (#179) activty 화면 cell 로드 애니메이션 수정
  BoostRunClub/Coordinators/AppCoordinator.swift
  BoostRunClub/Services/LocationProvider.swift
  BoostRunClub/Services/MapSnapShotService/RouteDrawer.swift
  BoostRunClub/Services/RunningService/RunningBoard.swift
  BoostRunClub/Services/RunningService/RunningRecoder.swift
  BoostRunClub/Services/RunningService/RunningServiceType.swift
  BoostRunClub/Views/Controllers/ActivityViewController.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
Labels: 0_Merge: master, 🏷️ bug :beetle:

#190 (#189) style: 다크모드 컬러셋 추가 및 적용
  BoostRunClub/Extensions/UIButton+setArrowImage.swift
  BoostRunClub/SupportingFiles/Assets.xcassets/Accent.colorset/Contents.json
  BoostRunClub/SupportingFiles/Assets.xcassets/Color.colorset/Contents.json
  BoostRunClub/SupportingFiles/Assets.xcassets/accent2.colorset/Contents.json
  BoostRunClub/SupportingFiles/Assets.xcassets/brcYellow.colorset/Contents.json
  BoostRunClub/Views/CircleButton.swift
  BoostRunClub/Views/Controllers/PausedRunningViewController.swift
  BoostRunClub/Views/Controllers/RunningInfoViewController.swift
  BoostRunClub/Views/Controllers/RunningPageViewController.swift
  BoostRunClub/Views/RunDataView.swift
Labels: 0_Merge: master, 🏷️ style :art:

#192 (#191) fix: 다크모드 및 라이트모드 toggle시 annotation이 바뀌는 버그 수정
  BoostRunClub/Views/ActivityDetailScene/DetailMapView.swift
  BoostRunClub/Views/Controllers/ActivityDetailViewController.swift
  BoostRunClub/Views/Controllers/RouteDetailViewController.swift
Labels: 0_Merge: master, 🏷️ bug :beetle:

#197 (#196)fix: pausedWorkout 사운드 문제
  BoostRunClub/Services/Provider/MotionDataModelProvider.swift
  BoostRunClub/Services/RunningService/RunningService.swift
  BoostRunClub/Services/RunningService/RunningServiceType.swift
  BoostRunClub/ViewModels/PausedRunningViewModel.swift
  BoostRunClub/ViewModels/RunningInfoViewModel.swift
  BoostRunClubTests/Mocks/RunningServiceTypeMock.swift
Labels: 0_Merge: master, 🏷️ bug :beetle:

#199 (#198) feat: split detail 데이터 바인딩
  BoostRunClub/Models/Activity.swift
  BoostRunClub/ViewModels/SplitInfoDetailViewModel.swift
  BoostRunClub/Views/DataSource/SplitDatailSplitDataSource.swift
Labels: 0_Merge: master
